name: farmer
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: any
  http: any
  simple_animations: any
  provider: any
  rflutter_alert: any
  smooth_star_rating: any
  url_launcher: any
  image_picker: any
  fluttertoast: any
  charts_flutter: any
  pie_chart: any
  flutter_money_formatter: any
  intl: any
  flutter_datetime_picker: ^1.4.0
  cached_network_image: any
  connectivity: any
  keyboard_dismisser: any
#  rate_my_app: 0.6.0+3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/peopleman.png
    - assets/images/logo.png
    - assets/images/maket.png
    - assets/images/people.png
    - assets/images/cherry.png
    - assets/images/seedling.png
    - assets/images/tea.png
    - assets/images/vegetable.png
    - assets/images/drink.png
    - assets/images/rice.png
    - assets/images/icons_empty.png
    - assets/images/star.png
    - assets/images/people_empty.png
    - assets/onboarding1.png
    - assets/topbg.png
    - assets/topbg3.png
    - assets/bottombg.png
    - assets/bottombg2.png
    - assets/bottombg3.png
    - assets/card.png
    - assets/market.png
    - assets/freedelivery.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
